# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc6ffead5634fef375588f9cad95b18fcf141d964b6432223670d8055f61680b21a855a020a0e2f0de0b3943b54fc3cb9a6028a5a9848120ec2249b9cded0aff

test:
  secret_key_base: 67b566b9a92d5f9a66340d1005cf1ca79fb31edbd1877c6bfd3becee592d9541ccef3ab981907513be28aad107f6f465aac44a770b29ca2e19114a93e819bc6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
