"""empty message

Revision ID: 7b0139dba050
Revises: 
Create Date: 2016-12-02 22:26:27.015648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0139dba050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Todo')
    # ### end Alembic commands ###
